site_name: Despliegue de aplicaciones web
site_url: https://jmunozji.github.io/DAW

theme:
  name: material
  logo: assets/logocaminas.png
  
  palette: 
    - media: "(prefers-color-scheme: light)"    
    # Palette toggle for light mode
      scheme: default
      primary: blue
      accent: green 
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
  language: es
  features:
    #- navigation.sections
    - navigation.top
    #- navigation.expand
    - toc.integrate
    - search.highlight
    - content.code.annotate
    - content.code.copy
markdown_extensions:
  - meta
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - footnotes
  
plugins: 
  - search:
      lang: es
  - awesome-pages:
      collapse_single_pages: true

extra_css:
  - stylesheets/extra.css

extra:
  analytics: 
      provider: google 
      property: G-3NX5MD5C8H

nav:
  - ... | Unidad 1/*.md
  - ... | Unidad 2/*.md
  - ... | Unidad 3/*.md
  - ... | Unidad 4/*.md
#  - Unidad 4:
#      - Teoría: 
#        - dns.md
#      - Prácticas:
#        - ... | P4.*.md
#  - Unidad 5:
#      - Teoría: 
#        - index_git.md
#       - cvs.md
#        - introduccion.md
#        - git.md
#        - usobasico.md
#        - usoavanzado.md
#        - ramas.md
#        - github.md
#        - github-zenodo.md
#        - github-flow.md
#        - github-avanzado.md
#        - commands.md
#        - gitflow.md
#        - referencias.md
#      - Prácticas:
#       - ... | P5.*.md      
#  - Unidad 6:
#      - Teoría: 
#        - index_docker.md
#        - introduction.md
#        - installation.md
#        - images.md
#        - containers.md
#        - data.md
#        - wordpress.md
#        - docker-compose.md
#        - dockerfile.md
#        - tips.md
#      - Prácticas:
#        - ... | P6.*.md
#  - Unidad 7:
#      - Teoría: 
#        - cicd.md
#      - Prácticas:
#        - ... | P7.*.md    